tbf-challenge/teamwork-be

- .github/ISSUE_TEMPLATE/bug-report-template.md
- .github/ISSUE_TEMPLATE/epic-template.md
- .github/ISSUE_TEMPLATE/task-template.md
- .github/ISSUE_TEMPLATE/user-story-template.md
- .github/PULL_REQUEST_TEMPLATE.md
This pull request is to update the templates in the project.
>  update the templates in the project

- README.md
-   [ ] Your pull request targets the `main` branch.
-   [ ] Branch name is descriptive and follows the guidelines [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices).
-   [ ] All tests pass . Use `git commit --amend` to amend any fixes.
-   [ ] All tests are passing.
-   [ ] Tested changes locally.
-   [ ] Improved documentation or readme where necessary.
-   [ ] Your commit messages format follows our commit message guideline [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices#commits).
> update the project README.md

- migrations/1660757644069_db-init.js
Creates a new migration script for the database. This adds the autoincrement functionality for the IDs to the various tables.
1.  Drop the database teamwork.
2. Create a new database called teamwork
3. Start the server …
> initialize the database again

- package-lock.json
- package.json
- src/app.js
- src/db/index.js
- src/lib/logger.js
Fixes authentication issues between the app and the database.
https://github.com/salsita/node-pg-migrate/blob/master/docs/cli.md
An error was being recorded when connecting the db to the app
```
could not connect to …
```
> add reject unauthorised for secure connection

- src/routes/posts.js
Remove duplicate route from the post router
1. git fetch && git checkout branch
2. start the server with `npm run dev`
3. Make a request to any of the routes.
4. The request should be successful …
>  fix Error: router.route is not a function 

- src/routes/articles.js
- src/routes/index.js
- src/routes/posts.js
- src/services/posts.js
2. Create an account with sample data below (data must be unique) to this endpoint `http://localhost:3000/api/v1/auth/create-user`
```
{
"firstName" : "sample firstName",
"lastName" …
```
> enhancement(x): enhanced create post endpoint properties [Start #88]

- package.json
- src/middleware/isAuthenticated.js
- src/routes/articles.js
- src/routes/posts.js
- src/routes/tags.js
- src/routes/users.js
> feat(endpoint): add passport to routes[Finish #85]

- src/routes/articles.js
- src/routes/posts.js
- src/services/posts.js
1.  Start the server with `npm run dev`
2. Make a `GET` request to this endpoint `http://localhost:3000/api/v1/articles/13`
3. It successfully returns the sample data below
```
{
"status": "success",
"data": { …
```
> enhancement(x): enhanced the get article properties [Start #97]

- src/routes/articles.js
- src/routes/posts.js
- src/services/errors.js
- src/services/posts.js
2. Make a POST request with sample data below to this endpoint `http://localhost:3000/api/v1/articles/13/comment`
```
{
"userId" : 4 ,
"comment" : "Dragons"
}
```
3. This …
> enhancement(x):enhanced comment properties [Start #99]

- src/routes/articles.js
- src/routes/posts.js
- src/services/errors.js
- src/services/posts.js
This PR enhances the properties of the `Update Article Endpoint`
2. Make a PATCH request with sample data below to this endpoint …
> enhancement(x): enhanced update article properties [Start #102]

- src/routes/articles.js
- src/routes/posts.js
- src/services/posts.js
This PR refactors the delete article endpoint
2. Make a DELETE request to this endpoint `http://localhost:3000/api/v1/articles/<article:id>`
3. This successfully returns the sample …
> refactor(endpoint): refactored delete endpoint [Start #104]

- docs/swagger.yaml
- package-lock.json
- package.json
- src/app.js
Add documentation for the API for the creation of user and article endpoints
1. git fetch && git checkout branch
2. npm run dev
3.  view documentation http://localhost:3000/docs/#/ …
> Doc add documentation 

- src/controllers/index.js
- src/controllers/tags.js
- src/routes/tags.js
- src/services/errors.js
- src/services/tags.js
This PR refactors the tag functionality to use services i.e separates the business logic, the application logic and the routes to make it cleaner, easier to debug and more testable
No it doesn't
> 94 refactor tagging functionality to use services

- src/lib/schema.js
This PR return a clear and concise message to users when the password fails validation
2. Make a POST request with the sample data below to this endpoint …
> feature(format):Legible password format [Start #96]

- src/routes/articles.js
- src/routes/posts.js
- src/services/posts.js
-   [ ] Tested changes locally.
-   [ ] Improved documentation or readme where necessary.
This PR refactors delete tag post to use services
1. Start server with `npm run dev`
2. You will notice we have the logic for the  deleteTagPosts in the services folder
> refactor(x): refactor delete tags to use services [Start #113]

- src/routes/articles.js
- src/routes/posts.js
- src/services/posts.js
-   [] Tested changes locally.
This PR refactors the get all articles with same tag endpoint to use services
1. Start server with `npm run dev`
2. You will notice that the logic for  get all articles with same tag endpoint is in the services
I had to …
> refactor(x) refactor get articles with same tag [Start #115]

- src/lib/custom-error.js
- src/routes/articles.js
- src/routes/posts.js
- src/services/errors.js
- src/services/posts.js
- src/services/tags.js
-   [] Tested changes locally.
This PR refactors assign tag to post to use services
1. Start server with `npm run dev`
2. You will notice the logic of the assign tag to post endpoint uses services
The plan was to refactor the assign tag to post so it …
> refactor(x): refactor assign tag to post to use services [Start #117]

- src/db/index.js
- src/lib/index.js
- src/lib/schema.js
- src/middleware/global-errorhandler.js
- src/middleware/validateSchema.js
- src/routes/articles.js
- src/routes/auth.js
- src/schema.js
- src/server.js
-   [] Tested changes locally.
This PR validates article updates endpoint
1. Start server with` npm run dev `
2. Make a PATCH request with sample data to this endpoint  
3. This successfully returns `Article successfully updated`
Ensure that article …
> feature(validation): validate article updates [Start #119]

- src/routes/articles.js
- src/schema.js
This PR validates the Create Comment endpoint data
2. Send the sample data below to this endpoint` http://localhost:3000/api/v1/articles/13/comment`
```
{
"userId" : 4 ,
"comment" : …
```
> feature(validation): validate create comment data [Start #121]

- src/routes/tags.js
- src/schema.js
This PR validates data in the Tag Creation Process
1. Start server with `npm run dev`
2. Make a POST request with the sample data below to this endpoint `http://localhost:3000/api/v1/tags`
```
{
"content" : "Go",
"title" …
```
> feature(validation): validate create tag data [Start #127]

- src/routes/tags.js
- src/schema.js
This PR validates tag updates data
1.Start the server with `npm run dev`
2. Make a PATCH request with the sample data below to this endpoint ` http://localhost:3000/api/v1/tags/3` 
```
{   
"content" : "world",
"title" : …
```
> feature(validation): validate update tag data [Start #129]

- src/routes/tags.js
- src/schema.js
This PR validates delete requests
2. Make a DELETE request to this endpoint `http://localhost:3000/api/v1/tags/5`
3. This successfully returns `success`
4. To test the validation of …
> feature(validation): validate delete tag data [Start #132]

- src/routes/articles.js
- src/schema.js
This PR validates Delete Article Tags Request
1. Start the server with  ` npm run dev`
2. Make a DELETE request to this endpoint `http://localhost:3000/api/v1/articles/13/tags/4`
3. This successfully returns `Tag Has …
> feature(validation): validate delete tag request [Start #137]

- src/routes/articles.js
- src/schema.js
This PR validates the query article tag requests
2. Make a GET request to this endpoint `http://localhost:3000/api/v1/articles/query/?tag=2`
3. Play with the query and you will see …
> feature(validation): validate query article tag request [Start #139]

- src/routes/posts.js
- src/services/posts.js
2. You will realize the query code assign tags article refactor
> Rf query code assign tags article 147

- migrations/1661202676736_drop-content-and-title-columns-from-posts-tags-table.js
- migrations/1662648153132_create-unique-constraint-for-title-in-tags-table.js
- src/services/tags.js
> refactor(x): refactor code for creating tags [Start #150]

- src/middleware/isAdmin.js
- src/routes/auth.js
This PR adds a new isAdmin middleware that checks if a user's job role is 'admin' and adds it to the createuser route
1. npm run dev
2.  Sign in as a normal user
3. …
> create isAdmin middleware and add it to create user route

- README.md
This adds a guide on how to create a migration to update the database
> Add migration guide to README

- migrations/1662985386038_make-certain-fields-optional-on-users-table.js
- src/schema.js
This pr makes certain fields optional on users table 
2. Make a POST request with the sample data below to this endpoint` http://localhost:3000/api/v1/auth/create-user`
```
{ …
```
> feature(x):make certain fields optional on users table [Start #160]

- migrations/1663002357449_make-content-column-optional-in-tags-table.js
- src/schema.js
makes content column optional in tags table
making content column optional in tags table
>  feature(x): make content column optional in tags table [Start #154]

- package-lock.json
- package.json
- src/scripts/adminuser.js
- src/scripts/insertAdminUser.js
script to add admin user to database
1. Insert the data by running this command `node src/scripts/adminuser`
script to add admin user to database
> script to add admin user to database

- .env.sample
- src/lib/email-lib.js
This PR updates the env parameters for the email library
1. npm run dev
2. add your mail service envs to your env file
3. test /auth/invite-user
The environment …
> 176 update nodemailer configuration parameter for production

- src/lib/passport-jwt.js
- src/services/users/index.js
This PR resolves newly generated token from auth/token endpoint not working
2. Make a GET request to this endpoint `http://localhost:3000/api/v1/feed`
3. This successfully returns …
> newly generated token from auth/token endpoint not working

- docs/swagger.yaml
- src/routes/articles.js
- src/routes/gifs.js
- src/routes/index.js
- src/schema.js
- src/services/errors.js
- src/services/posts.js
This PR creates gif endpoint
2. Make a POST request with sample data below to this endpoint `http://localhost:3000/api/v1/gifs`
```
{
"userId" : 4,
"title" : "mygiff",
"image" : …
```
> feature(endpoint): create gif endpoint [Start #184]

- .gitignore
- .mocharc.js
- README.md
- package.json
- src/config.js
- test/pretest.js
- test/utils.js
This involve setting up the test utils for writing the tests
1. Pull the branch 
2. Run `npm run test`
Related Issues
https://github.com/tbf-challenge/teamwork-be/issues/175
> Setup test utils

- docs/swagger.yaml
- src/routes/articles.js
- src/routes/gifs.js
- src/schema.js
- src/services/errors.js
- src/services/posts.js
Get's gif by ID
1. Start the server with `npm run dev
2. Make a GET request to this endpoint` http://localhost:3000/api/v1/gifs/1`
3. This successfully returns `success`
Get gif by id
> Get gif by id

- docs/swagger.yaml
- package-lock.json
- package.json
- src/routes/articles.js
- src/routes/gifs.js
- src/services/posts.js
- src/services/posts/delete-post.js
- src/services/posts/delete-post.test.js
- src/services/posts/index.js
- test/utils.js
This PR deletes a gif by id
1. Start the server with `npm run dev
`2. Make  DELETE request to this endpoint `http://localhost:3000/api/v1/gifs/<gifid>
`3. This successfully returns `GIF image has been successfully …
> feature(endpoint) delete gif endpoint [Start #188]

- src/routes/gifs.js
> make changes to getPost [Start #203]

- docs/swagger.yaml
- src/routes/articles.js
- src/routes/gifs.js
- src/services/errors.js
- src/services/posts/create-comment.js
- src/services/posts/create-comment.test.js
- src/services/posts/index.js
- test/utils.js
This PR is used to make comments on gifs
1. Start server with npm run dev
2. Make a POST request with sample data below to this endpoint` http://localhost:3000/api/v1/gifs/47/comment`
```
{   
"userId" : 4,
"comment" : …
```
> Endpoint for creating comments on gifs 

- migrations/1664273420286_add-table-to-record-likes-on-posts.js
adds table to record likes on posts
1. Start the server with `npm run dev`, this should add the migration to your db
we needed to add table to record likes on posts
> add record likes table [Start #207]

- migrations/1664278604452_add-table-to-record-flagged-posts.js
add table to record flagged posts
1. Start the server with `npm run dev` and you will see the migration being added to the database
add table to record flagged posts
> add table to record flagged posts [Start #208]

- docs/swagger.yaml
- src/routes/articles.js
- src/routes/gifs.js
- src/schema.js
- src/services/errors.js
- src/services/posts/like-post.js
- src/services/posts/like-post.test.js
record likes on article endpoint 
2. Make a POST request with the sample data below to this endpoint `http://localhost:3000/api/v1/articles/13/likes`
```
{   
"userId" : 4
}
```
3. …
> record likes on article endpoint 

- .mocharc.js
- docs/swagger.yaml
- src/routes/gifs.js
- src/routes/gifs/index.js
- src/routes/gifs/unlike-gif.e2e.test.js
- src/schema.js
- src/services/posts/index.js
- src/services/posts/unlike-post.js
- src/services/posts/unlike-post.test.js
- test/utils.js
Endpoint for unliking a gif
1, Start the server with `npm run dev`
2. Make a DELETE request to this endpoint `http://localhost:3000/api/v1/gifs/:id/likes/:userId`
3. This should return `success`
Endpoint for unliking a …
> Endpoint for unliking a gif

- src/config.js
adds a validation to to config variables
1. npm run test
2. npm run dev
> add validation to config

- src/routes/auth.js
Corrects unexpected error about email in create user endpoint
> unexpected error about email 

- src/middleware/isValidInvite.js
- src/routes/auth/create-new-user.e2e.test.js
- src/routes/auth/index.js
- test/utils.js
adds a test to the create-new-user route
1. npm run test
> 198 test create user endpoint

- docs/swagger.yaml
- src/routes/articles/flag-article.e2e.test.js
- src/routes/articles/index.js
- src/services/errors.js
- src/services/posts/flag-post.js
- src/services/posts/flag-post.test.js
This PR is the endpoint for flagging inappropriate articles
2. Make a` POST` request with sample data below to this endpoint `http://localhost:3000/api/v1/articles/14/flags
````
{ …
```
> flag article endpoint 

- docs/swagger.yaml
- src/routes/auth/index.js
- src/services/users/index.js
This PR adds user details to the response body when a user signs in
2. Make a `POST` request with sample data below to this endpoint `http://localhost:3000/api/v1/auth/signin
{ …
> made additions to response body of auth/signin

- docs/swagger.yaml
- src/routes/articles/index.js
- src/routes/articles/unflag-article.e2e.test.js
- src/services/posts/unflag-post.test.js
This PR adds an endpoint to unflag an article
1. npm run test
> 225 endpoint to unflag an article

- migrations/1665144863994_seed-db-with-predefined-tags.js
This PR seeds the db with predefined tags
2. In the logs you will see the predefined tags being inserted into the db
3. You can also use pgadmin to look for the tags on the tags …
> seed the db with predefined tags 

- docs/swagger.yaml
- src/controllers/tags.js
- src/routes/tags/delete-tag.e2e.test.js
- src/routes/tags/index.js
- src/services/tags/delete-tag.js
- src/services/tags/delete-tag.test.js
- src/services/tags/index.js
- test/utils.js
fixes the delete tag bug
1. npm run test
> 248 delete tag endpoint does not delete the tag

- src/routes/auth/index.js
- src/services/users/index.js
- src/services/users/update-refresh-token.js
This PR resolves the invalid refreshToken bug
1. Make a POST request with data to signin to the app to this endpoint `http://localhost:3000/api/v1/auth/signin`
2. This returns accessToken and refreshToken
3. Using the …
> resolved invalid refreshToken bug 

- docs/swagger.yaml
This PR updates all missing endpoint documentation
2. Open this link in the browser to see the updated endpoint  [http://localhost:3000/docs/#/](http://localhost:3000/docs/#/)
We …
> update documentation with up to date documentation

- docs/swagger.yaml
This PR includes the get all tags documentation
1. Start the server with` npm run dev`
2. Copy and paste this link in the browser to see the get all tags endpoint documentation `http://localhost:3000/docs/#/tag/getTags` …
> included get all tags documentation 

- docs/swagger.yaml
This PR resolves bug in the get all tags documentation
2. Paste this link in the browser to see the response body of get all tags documentation …
> resolve bug in the get all tags documentation

- docs/swagger.yaml
- src/routes/auth/create-new-user.e2e.test.js
- src/routes/common/transformers.js
- src/routes/users/fetch-users.e2e.test.js
- src/routes/users/index.js
- src/services/users/fetch-users.js
- src/services/users/fetch-users.test.js
- src/services/users/index.js
- test/utils.js
This PR fetches all users from the database
2. Make a` GET `request to this endpoint `http://localhost:3000/api/v1/users`
3. This successfully returns the users in the database
We …
> get all employees endpoint

- src/routes/articles/create-article.e2e.test.js
- src/services/posts/create-post.js
- src/services/posts/create-post.test.js
- src/services/posts/index.js
This PR tests the create article endpoint
1. Start the test with npm run test
2. This should successfully test all endpoints and services
We had to test the create article endpoint
> create article endpoint test

- src/routes/tags/fetch-tags.e2e.test.js
- src/services/tags/fetch-tags.js
- src/services/tags/fetch-tags.test.js
- src/services/tags/index.js
- test/utils.js
This PR tests the fetch tags services and endpoint
2. This successfully returns `passed `
We had to test the get all tags endpoint and services
> get tags endpoint test

- src/routes/articles/update-article.e2e.test.js
- src/services/posts/index.js
- src/services/posts/update-post.js
- src/services/posts/update-post.test.js
This PR adds api and service testing for the Update Article Endpoint
1. Start the test with` npm run test`
2. This should return all tests passing 
We had to include api and service testing for the `Update Article …
> Update article endpoint testing

- src/routes/auth/index.js
This PR ensures auth/token returns the right data
1. Make a `POST` request to `http://localhost:3000/api/v1/auth/token` with the sample data below
```
{
"email" : "example@gmail.com",
"refreshToken : …
```
> resolve auth token bug

- src/routes/auth/index.js
- src/routes/auth/signin-user-by-email.e2e.test.js
- src/routes/auth/signin.e2e.test.js
- src/services/users/get-user-by-email.js
- src/services/users/index.js
- src/services/users/signin-user-by-email.js
- src/services/users/signin-user-by-email.test.js
This PR tests the user signin endpoint and service
2. This should return `all test passed `
We had to test the signin endpoint and service
> User signin endpoint test

- docs/swagger.yaml
- src/routes/posts.js
- src/services/posts/index.js
This PR returns author information as part of the feed endpoint
2. Make a `GET` request to this endpoint http://localhost:3000/api/v1/feed
3. This returns the sample data below
``` …
```
> add author information to feed endpoint 

- docs/swagger.yaml
- src/routes/posts.js
- src/services/posts/index.js
We added the userId to the feed endpoint
2. Make a GET request to this endpoint  `http://localhost:3000/api/v1/feed`
3. This successfully returns the sample data below
```
{
"status": …
```
> added userId to the feed endpoint

- src/routes/articles/create-article.e2e.test.js
- src/schema.js
This PR resolves the bug in the POST articles/gifs endpoints
1. Make a POST request with sample data below to this endpoint `http://localhost:3000/api/v1/articles/gifs`
```
{
"title" : "carl is",
"article" : …
```
> resolved bug in the POST articles/gifs

- .github/workflows/test.yml
All failed jobs to run to completions.
1. View the build here: https://github.com/tbf-challenge/teamwork-be/actions/runs/3355660161/jobs/5560093490
2. the jobs for node -versions 16 and 18 passed whiles 14 failed due to …
> allow failed jobs to run to completions

- src/routes/articles/create-article.e2e.test.js
- src/routes/articles/update-article.e2e.test.js
- src/routes/auth/create-new-user.e2e.test.js
- src/routes/users/update-user.e2e.test.js
- src/schema.js
- test/utils.js
… increasing the text for the article title
Fix flakey test for creation of articles, creation of users, etc. This is because there is a minimum length required. 
However, using the faker is being used, randomly the …
>  fix flaky test 

- docs/swagger.yaml
- src/routes/auth/get-invited-user-detail.e2e.test.js
- src/services/users/get-invited-user-detail.js
- src/services/users/get-invited-user-detail.test.js
- src/services/users/index.js
- test/utils.js
We are testing the auth/invites/token endpoint and service
2. Make a `POST` request with sample data below to this endpoint `http://localhost:3000/api/v1/auth/invite-user`
```
{ …
```
> get user invite information test 

- docs/swagger.yaml
- src/routes/gifs/create-gif.e2e.test.js
- src/routes/gifs/index.js
This PR tests the create gif endpoint
2. This successfully returns all test passing
we had to test the create gif endpoint
> create gif endpoint test 

- src/routes/articles/delete-article.e2e.test.js
- src/services/posts/delete-post.test.js
It adds test to delete article endpoint
2. This should return all tests passing
We had to test for the delete article endpoint
> delete article endpoint test 

- src/routes/articles/get-article.e2e.test.js
- src/services/posts/get-post.js
- src/services/posts/get-post.test.js
- src/services/posts/index.js
- test/utils.js
This PR tests the get article endpoint and get post services
2. This successfully returns all tests passing
We had to test the get article endpoint and get post services
> get article test 

- src/routes/gifs/delete-gif.e2e.test.js
This PR tests the delete gif endpoint
1. Start the test with` npm run test`
2. This successfully returns all tests passing
We had to test the delete gif endpoint
> delete gif endpoint test

- src/routes/tags/update-tag.e2e.test.js
- src/services/tags/index.js
- src/services/tags/update-tag.js
- src/services/tags/update-tag.test.js
This PR tests the update tag endpoint and services
2. This should successfully return all tests passing
we had to test the update tag endpoint and services
> update tag testing

- src/routes/articles/create-article.e2e.test.js
-   [ ] All tests are passing.
-   [ ] Tested changes locally.
-   [ ] Improved documentation or readme where necessary.
-   [ ] Your commit messages format follows our commit message guideline [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices#commits).
The test for creation of new article fails. This PR adds a logger to the test inorder to monitor this in the CI and appreciate better why it falis. The reason the log was added is that the test is flaky and after trying …
>  add logs to flaky test

- docs/swagger.yaml
-   [ ] All tests are passing.
-   [ ] Tested changes locally.
Improves the documentation by adding the bearer authentication
1. ``` git fetch && git checkout  ch-use-right-authentication-specification-in-docs-241```
2.  Start the server with npm start
3.  Navigate in the browser to …
> update the security in the documentation with bearerAuth

- src/routes/tags/fetch-tags.e2e.test.js
- src/services/tags/fetch-tags.test.js
The success block was declared within the failure block. This PR fixes it so that the two blocks are declared separately
2. This successfully returns all test passing 
The success …
> fixed flaky test for tags

- src/services/posts/create-comment.js
- src/services/posts/create-post.js
- src/services/posts/flag-post.js
- src/services/posts/get-post.js
- src/services/posts/like-post.js
- src/services/posts/update-post.js
This PR selects and returns specific fields on the post table
2 Go through the code to see the differences in select and return queries …
> return specific fields on posts table

- migrations/1668021210259_add-new-column-to-track-likes-on-a-post.js
- src/services/posts/create-comment.test.js
- test/utils.js
https://github.com/tbf-challenge/teamwork-be/issues/305
1. Start the server` npm run dev`
2. You will see the column being created in the terminal logs
https://github.com/tbf-challenge/teamwork-be/issues/305
> add likes count column on post 

- .mocharc.js
- package-lock.json
- package.json
- src/lib/email-lib.js
- src/routes/auth/invite-user.e2e.test.js
- src/services/email-templates.js
- src/services/users/index.js
- src/services/users/invite-user.js
- src/services/users/invite-user.test.js
- test/stub-mailer.js
This PR tests the invite-user endpoint and service
2. This should return all `tests passing `
We had to test the `invite-user endpoint` and service
> Invite user endpoint and service test 

- migrations/1668439124477_add-trigger-function-to-compute-flagsCount-on-posts.js.js
- src/services/posts/flag-post.js
- src/services/posts/flag-post.test.js
- src/services/posts/unflag-post.js
- src/services/posts/unflag-post.test.js
https://github.com/tbf-challenge/teamwork-be/issues/308
2. In the logs in the terminal we see a new migration has been added to the database …
> record number of flags 

- src/routes/gifs/like-gif.e2e.test.js
https://github.com/tbf-challenge/teamwork-be/issues/318
2. This should return all tests passing
https://github.com/tbf-challenge/teamwork-be/issues/318
> add test to like gif endpoint

- docs/swagger.yaml
- src/routes/common/transformers.js
https://github.com/tbf-challenge/teamwork-be/issues/320
2. Make a GET request to this endpoint http://localhost:3000/api/v1/gif/:gifId
3. This successfully return the sample data …
> add likes count to get gif endpoint 320

- src/routes/gifs/get-gif.e2e.test.js
https://github.com/tbf-challenge/teamwork-be/issues/324
1. Start the server with `npm run test`
2. This should return all tests passing 
https://github.com/tbf-challenge/teamwork-be/issues/324
> added test to get gif endpoint

- docs/swagger.yaml
- src/services/posts/index.js
https://github.com/tbf-challenge/teamwork-be/issues/327
2. Make  `GET` request to this endpoint http://localhost:3000/api/v1/feed
3. This successfully returns the sample data below …
> add likesCount to get feed endpoint 327

- docs/swagger.yaml
- src/middleware/isFlaggedAndIsAdmin.js
- src/routes/common/transformers.js
- src/routes/fetch-posts.e2e.test.js
- src/routes/posts.js
- src/schema.js
- src/services/posts/fetch-posts.js
- src/services/posts/fetch-posts.test.js
- src/services/posts/index.js
- test/utils.js
https://github.com/tbf-challenge/teamwork-be/issues/326
2. Make a `GET` request to this endpoint http://localhost:3000/api/v1/feed?isFlagged=true
3. This should return all posts …
> query all flagged post 326

- src/routes/articles/assignTagToArticle.e2e.test.js
- src/services/posts/assign-tag-to-post.js
- src/services/posts/assign-tag-to-post.test.js
- src/services/posts/index.js
- test/utils.js
https://github.com/tbf-challenge/teamwork-be/issues/331
2. This should return all tests passing
https://github.com/tbf-challenge/teamwork-be/issues/331
> add test to assign tag to post 

- src/routes/articles/deleteArticleTag.e2e.test.js
- src/services/posts/delete-post-tag.js
- src/services/posts/delete-post-tag.test.js
- src/services/posts/index.js
1. Moved the delete post tag function to a separate file
2. Added test to the delete post tag service
3. Added endpoint testing to the delete article tag endpoint
https://github.com/tbf-challenge/teamwork-be/issues/334 …
> delete post tags endpoint testing 

- src/routes/articles/queryArticleTag.e2e.test.js
- src/services/posts/index.js
- src/services/posts/query-post-tags.js
- src/services/posts/query-post-tags.test.js
- src/services/tags/update-tag.test.js
1. Added endpoint test to query article tag endpoint
2. Added test to query post tag service function
3. Moved the query post tag function into its own file
https://github.com/tbf-challenge/teamwork-be/issues/336
1. …
> add test to query article tags endpoint

- docs/swagger.yaml
- src/routes/posts.js
- src/schema.js
- src/services/posts/fetch-posts.js
- src/services/posts/fetch-posts.test.js
https://github.com/tbf-challenge/teamwork-be/issues/338
2. Make a GET request with query params to this endpoint  `http://localhost:3000/feed?isFlagged=true&cursor=1&limit=1`
3. This …
> Ft implement pagination 338
